apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-app
  template:
    metadata:
      labels:
        app: broker-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: broker-app
          image: broker-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
